version: {build}
image: Visual Studio 2017
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: choco install maven
  
# to disable automatic builds by MsBuild
build: off

test_script:
  - mvn test